### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by Jack-Works** [bterlson/eshost-cli#79]
> eshost --configure-jsvu
```
Using config "C:\Users\Jack\.eshost-config.json"
Configuring jsvu host with name "ChakraCore" (type "ch") at "C:\Users\Jack\.jsvu\chakra.cmd"
Host "ChakraCore" already exists
C:\Users\Jack\AppData\Roaming\npm\node_modules\eshost-cli\lib\host-manager.js:172
    ] = VU_HOST_DETAILS[vu][engine];
        ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.exports.configureFromVersionUpdater (C:\Users\Jack\AppData\Roaming\npm\node_modules\eshost-cli\lib\host-manager.js:172:9)
    at Object.<anonymous> (C:\Users\Jack\AppData\Roaming\npm\node_modules\eshost-cli\bin\eshost.js:294:15)
```

**Comment by rwaldron** [comment]
There's not enough information here for me to act on. If you can provide the contents of the .jsvu config file, that would be helpful. Thanks.

**Comment by Jack-Works** [comment]
`~/.jsvu` on my computer is a folder.

> `~/.jsvu/status.json`

```json
{
	"os": "win64",
	"engines": [
		"chakra",
		"hermes",
		"quickjs",
		"spidermonkey",
		"v8",
		"xs"
	],
	"chakra": "1.11.23",
	"hermes": "0.7.1",
	"spidermonkey": "84.0b2",
	"v8": "8.9.7",
	"xs": "10.4.0"
}
```

I have patched `node_modules` to add a try-catch on those failing lines and get my eshost configured.

**Comment by rwaldron** [comment]
```
npm install eshost-cli@7.6.1
```

Let me know if the issue still exists

**Comment by Jack-Works** [comment]
sorry this still happens in 7.6.1

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/108169683-ff929780-7133-11eb-91e5-7c972f6fb4fa.png)

I guess you should check `VU_HOST_DETAILS[vu][engine]` too

**Comment by rwaldron** [comment]
```
npm install eshost-cli@7.6.2
```

Please confirm

**Comment by rwaldron** [comment]
Latest is now `npm install eshost-cli@7.6.3`

**Comment by Jack-Works** [comment]
```
Using config "C:\Users\Jack\.eshost-config.json"
Configuring jsvu host with name "ChakraCore" (type "ch") at "C:\Users\Jack\.jsvu\chakra.cmd"
Configuring jsvu host with name "Hermes" (type "hermes") at "C:\Users\Jack\.jsvu\hermes.cmd"
C:\Users\Jack\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\registry.npmjs.org\eshost-cli@7.6.3\node_modules\eshost-cli\lib\host-manager.js:191
    const version = status[engine] || (status.installed[engine] && status.installed[engine].version);
                                                       ^

TypeError: Cannot read property 'javascriptcore' of undefined
    at Object.exports.configureFromVersionUpdater (C:\Users\Jack\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\registry.npmjs.org\eshost-cli@7.6.3\node_modules\eshost-cli\lib\host-manager.js:191:56)
    at Object.<anonymous> (C:\Users\Jack\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\registry.npmjs.org\eshost-cli@7.6.3\node_modules\eshost-cli\bin\eshost.js:294:15)
```
